### ISSUE TITLE
Turning a flat point to corner fails

### ISSUE THREAD

**Issue by raphaelbastide** [mattlag/Glyphr-Studio#142]
When a curve point is changed to corner, the point’s handles remains.

**Comment by mattlag** [comment]
"Corner" in this case means the two handles can be moved independently. As opposed to "Flat" or "Symmetric" where moving one handle moves the other handle as well.

Separate from this functionality is the check box in the details pane next to 'handle 1' and 'handle 2' that shows or hides the handles.

**Comment by davelab6** [comment]
RB, do you mean to make a point with 2 straight lines to it?

**Comment by raphaelbastide** [comment]
@davelab6 Yes, just like the icon on Inkscape “Make Selected Nodes Corner”

**Comment by mattlag** [comment]
If there is a better or more common word for this, then i'd be happy to change it :-) 

Right now there is one property of a point which is "Type" and they are Symmetric, Flat, and Corner.  There are two completely separate properties of "Show Handle 1" and "Show Handle 2".  

There is some logic here - for example, if the Type = Symmetric, then I disable the "Show Handle" checkboxes, because Symmetric point it only makes sense to show each handle.  But for Flat and Corner types, each Handle can be shown or hidden independently.  

A strange case is if the type is "Flat" and you hide Handle 1 (for example) and move Handle 2, Handle 1 is still updated.

If you create a new rectangle, for example, the corner points are Type=Corner with both Handles hidden.

I think in vector programs, there isn't quite this concept of choosing to use 0, 1, or 2 handles per point.  On Dave's suggestion, i'm going to take a little time and use some other font design tools (like FontForge) to see how stuff works other places.  But, if you have any ideas on how to make this more understandable, i'd love to hear suggestions!

Thanks, guys!  I hope your holidays and new year went well :-)
