### ISSUE TITLE
History: Group actions by category (set of similar actions) and time (bursts of activity)

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#182]
Following on from https://github.com/mattlag/Glyphr-Studio/issues/181, in a long-running project, the undo-redo history becomes very very long. 

Google Docs has a good feature where it allows users a button to `show more/less activity`:

![screen shot 2015-05-09 at 2 53 00 am](https://cloud.githubusercontent.com/assets/261579/7548168/0f154ee6-f5f7-11e4-84b2-38a904b6f25b.png)
![screen shot 2015-05-09 at 2 53 23 am](https://cloud.githubusercontent.com/assets/261579/7548169/0f18e8d0-f5f7-11e4-8404-313a4cff25e4.png)
![screen shot 2015-05-09 at 2 53 29 am](https://cloud.githubusercontent.com/assets/261579/7548167/0f124714-f5f7-11e4-8673-abc57a3fc6d3.png)
![screen shot 2015-05-09 at 2 57 42 am](https://cloud.githubusercontent.com/assets/261579/7548171/32c18bb6-f5f7-11e4-8772-0db534f392e0.png)

I suggest that actions can be grouped by category (a set of similar actions) and time (a burst of activity). 

For example, all the path editing could be folded up into a 'action group':

![screen shot 2015-05-09 at 2 50 08 am](https://cloud.githubusercontent.com/assets/261579/7548178/67175cc4-f5f7-11e4-80ae-fbe1be003225.png)

And then, after say 24 hours, the entire set of actions could be further folded up into 'Edited A`

**Comment by mattlag** [comment]
Currently, Undo History is only remembered per browser session.  If you save then re-import, history starts fresh.  That's because each history step is a full copy of the project at that point.

In the future, this will allow restoring a history point a number of steps back.  The downfall is that undo history memory usage is huge.

Right now history is grouped by letter, by nav.  So if you edit Glyph A, then edit Glyph B, then Edit Glyph A again, that will be three groups.
